package cc.dvitski.tabyproto

enum class RawAnimation(val id: String) {
    ANGRY_01_LOOP("angry_01_loop"),
    ANGRY_02_LOOP("angry_02_loop"),
    BASKETBALL_DUNK("basketball_dunk"),
    BASKETBALL_THROW("basketball_throw"),
    BLUSH("blush"),
    BOXING("boxing"),
    BREAK_START("break_start"),
    BUSY_LOOP("busy_loop"),
    CALENDAR_IN("calendar_in"),
    CALENDAR_LOOP("calendar_loop"),
    CIRCLE("circle"),
    CLAUDE_IN("claude_in"),
    CLAUDE_LOOP("claude_loop"),
    CODEX_IN("codex_in"),
    CODEX_LOOP("codex_loop"),
    CONFIRMATION("confirmation"),
    COPY_PASTE("copy_paste"),
    CREATING_TASK_LOOP("creating_task_loop"),
    DAY_PLANNED("day_planned"),
    DELETE_01("delete_01"),
    DISAPPOINTED("disappointed"),
    DIZZY_LOOP("dizzy_loop"),
    DRINK_WATER("drink_water"),
    F1_CAR("f1_car"),
    FISHING_LONG("fishing_long"),
    FISHING_SHORT("fishing_short"),
    FLOWER_GROW("flower_grow"),
    HELLO_ANNOYED("hello_annoyed"),
    HELLO_DISAPPOINTED("hello_disappointed"),
    IDLE_01_LOOP("idle_01_loop"),
    IDLE_02_LOOP("idle_02_loop"),
    IDLE_VARIATION_LOOP("idle_variation_loop"),
    LISTENING_IN("listening_in"),
    LISTENING_LOOP("listening_loop"),
    LISTENING_MUSIC_LOOP("listening_music_loop"),
    LOCKIN("lockin"),
    LOVE_01("love_01"),
    NO("no"),
    PERFECT_DAY_01("perfect_day_01"),
    PERFECT_DAY_01_SIMPLE("perfect_day_01_simple"),
    PERFECT_DAY_02("perfect_day_02"),
    PERFECT_DAY_03("perfect_day_03"),
    POSTURE_CHECK("posture_check"),
    RELAXING_01_LOOP("relaxing_01_loop"),
    RELAXING_COUCH_IN("relaxing_couch_in"),
    RELAXING_COUCH_LOOP("relaxing_couch_loop"),
    REVIEW("review"),
    SLEEPING_LOOP("sleeping_loop"),
    SQUARE("square"),
    STARTUP("startup"),
    STRETCHING("stretching"),
    TABY_RESPONSE_READY_IN("taby_response_ready_in"),
    TABY_RESPONSE_READY_LOOP("taby_response_ready_loop"),
    TALKING_DEFAULT_LOOP("talking_default_loop"),
    TALKING_MAN_LOOP("talking_man_loop"),
    TASK_COMPLETED("task_completed"),
    TASK_CREATED("task_created"),
    TASK_PAGE("task_page"),
    THUMBS_UP("thumbs_up"),
    TROPHY("trophy"),
    TURN_OFF_REDDIT("turn_off_reddit"),
    TURN_OFF_SCROLL("turn_off_scroll"),
    TURN_OFF_TV("turn_off_tv"),
    WAITING_01("waiting_01"),
    WORKING_IN("working_in"),
    WORKING_LAPTOP_BORED_LOOP("working_laptop_bored_loop"),
    WORKING_LAPTOP_EXCITED_LOOP("working_laptop_excited_loop"),
    WORKING_LAPTOP_IN("working_laptop_in"),
    WORKING_LAPTOP_LOOP("working_laptop_loop"),
    WORKING_LAPTOP_NORMAL_LOOP("working_laptop_normal_loop"),
    WORKING_LOOP("working_loop"),
    WORKSPACES_IN("workspaces_in"),
    WORKSPACES_LOOP("workspaces_loop"),
    WOW("wow"),
    YEAH("yeah"),
}

data class AnimationCommand(val from: RawAnimation, val to: RawAnimation) {
    internal fun toWireString() = "${from.id}>${to.id}"
}

infix fun RawAnimation.then(next: RawAnimation) = AnimationCommand(this, next)
